AIRO-1436: Mesh Generator Tool
Unity-Technologies/VHACD-deprecated pull request #6
Opened 2021-11-03 17:45 UTC by at669

## Proposed change(s)

This PR introduces the initial prototype for the mesh generation tool, with Single and Batch modes.

https://user-images.githubusercontent.com/31416491/140162987-104d4aad-8553-433c-9593-3bc847f85efb.mov

### Types of change(s)

- [x] New feature
- [x] Documentation update

## Testing and Verification

### Test Configuration:
- Unity Version: 2020.3.19f
- Unity machine OS + version: MacOS 10.15.7

## Checklist
- [x] Ensured this PR is up-to-date with the `mesh-generator` branch
- [x] Created this PR to target the `mesh-generator` branch
- [x] Updated the documentation as appropriate

2021-11-04 22:13 UTC, Hunter-Unity requested changes

2021-11-04 22:13 UTC, Hunter-Unity commented on com.unity.robotics.vhacd/Editor/MeshDecomposerWindow.cs
> +                Debug.Log($"Generated {m_Settings.MeshCountTotal} meshes on {go.name}");
MeshCountTotal is incorrect. If i use a Max Convex Hulls: 4 on this chair it chops the chair up into 8 pieces but Debug says it generated 21 meshes
<img width="1382" alt="Screen Shot 2021-11-04 at 1 13 43 PM" src="https://user-images.githubusercontent.com/19273127/140416380-54fe4082-f54a-4e8c-8fb8-056b1c72edd4.png">

2021-11-04 22:13 UTC, Hunter-Unity commented on com.unity.robotics.vhacd/Editor/MeshDecomposerWindow.cs
> +                (uint)EditorGUILayout.IntField("Max Convex Hulls", (int)m_Parameters.m_maxConvexHulls);
Maybe this should be "Max Convex Hulls per MeshRenderer" so people don't assume this is per object

2021-11-04 22:13 UTC, Hunter-Unity commented on com.unity.robotics.vhacd/Editor/VhacdSettings.cs
> +        public string AssetSavePath { get; set; } = "Assets/Prefabs";
```suggestion
        public string AssetSavePath { get; set; } = "Assets/VHACD/Prefabs";
```

2021-11-04 22:13 UTC, Hunter-Unity commented on com.unity.robotics.vhacd/Editor/VhacdSettings.cs
> +        public string MeshSavePath { get; set; } = "Assets/Meshes";
```suggestion
        public string MeshSavePath { get; set; } = "Assets/VHACD/Meshes";
```

2021-11-04 22:13 UTC, Hunter-Unity commented on com.unity.robotics.vhacd/Editor/VhacdSettings.cs
> +        public string AssetSavePath { get; set; } = "Assets/Prefabs";
Maybe we should use a default VHACD directories to prevent cluttering up existing folders in a project

2021-11-04 22:13 UTC, Hunter-Unity commented on .github/pull_request_template.md
> +- [ ] Followed the style guidelines as described in the [Contribution Guidelines](https://github.com/Unity-Technologies/URDF-Importer/blob/main/CONTRIBUTING.md)
this mentions the URDF-Importer repo. is that intentional or is this leftover copypasta

2021-11-04 22:13 UTC, Hunter-Unity commented on README.md
> +    https://github.com/Unity-Technologies/VHACD.git?path=/com.unity.robotics.vhacd#amanda/mesh-generator
```suggestion
    https://github.com/Unity-Technologies/VHACD.git?path=/com.unity.robotics.vhacd#mesh-generator
```

2021-11-04 22:13 UTC, Hunter-Unity commented on com.unity.robotics.vhacd/Editor/MeshDecomposerWindow.cs
> +                    var path = $"{m_Settings.MeshSavePath}/{m_MeshObject.name}/{meshIndex}.asset";
any where we save stuff i think it would be good to put VHACD in the name so people don't get confused with their own "Meshes" directories
```suggestion
                    var path = $"{m_Settings.MeshSavePath}/VHACD_meshes/{m_MeshObject.name}/{meshIndex}.asset";
```

2021-11-05 21:42 UTC, at669 commented on com.unity.robotics.vhacd/Editor/MeshDecomposerWindow.cs
> +                    var path = $"{m_Settings.MeshSavePath}/{m_MeshObject.name}/{meshIndex}.asset";
by default, meshes will now save in:

`Assets/<ASSET_NAME>/VHACD/Meshes/TEMP` or `Assets/<ASSET_NAME>/VHACD/Meshes` depending on the mode

2021-11-17 02:27 UTC, Hunter-Unity commented
Setting OclAcceleration to 1 and then pressing Generate causes Editor crash. If it's not an easy fix let's just un-expose it in the editor and leave it set to 0

2021-11-17 20:15 UTC, Hunter-Unity approved these changes
Did processing tests in both Single and Batch mode. Looks great!

2021-11-17 20:21 UTC, merged